apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # Define your storage class (must match PV)
  resources:
    requests:
      storage: 1Gi # Request the same storage as the PV
